config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :sidekiqexemplos

  resources :products

  resources :criticas

  root 'products#index'

  mount Sidekiq::Web, at: '/sidekiq'

  get 'products/search'
  post 'products/search'

end

app/models/critica.rb
class Critica
  include Mongoid::Document
  field :content, type: String



  embedded_in :product
end

app/models/product.rb
class Product

  

  include Mongoid::Document
  field :name, type: String
  field :price, type: BigDecimal
  field :cor, type: String 
  field :descr, type: String

  embeds_many :criticas

  update_index('products#product'){self}


#metodo para o search com o elasticsearch
  def self.search(keyword)

  	product_id = ProductsIndex::Product.query(
  		multi_match:{

  			#desta forma (multi_match em vez de term) possibilita a pesquisa em dois campos diferentes
  			query: keyword,
  			type: "phrase_prefix", #para apanhar resultados em que o termo a pesquisar esteja numa palavra maior,  
  			fields: [:name, :cor, :descr]

  			} #para poder ter um resultado mas simples tirando info por agora desnecessaria

  	).map { |result|  
  				result.attributes["id"]

  			}
  			self.find(product_id)
  	
  end



end

app/models/review.rb
class Review
  include Mongoid::Document
  field :content, type: String

  
end

app/models/sidekiqexemplo.rb
class Sidekiqexemplo
  include Mongoid::Document
  field :tipo, type: String
  field :codigo, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def angular
    render 'layouts/application'
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token
  skip_before_filter :verify_authenticity_token
  skip_filter :verify_signed_out_user


  # GET /products
  # GET /products.json
  def index

    /# @products = Product.all
    respond_with(@products) do |format|
      format.json { render :json => @products.as_json }
      format.html
    end
   /#
    
    @prods= Product.all


    respond_to do |format|
       if params[:query]
       
        @prods = Product.search(params[:query])
        
        format.html { @products = Product.search(params[:query]) }
        format.json { render :json => @prods }  #@products = Product.search(params[:query]) 
      else
         @prods = Product.all
        #@products = Product.all
        format.html { @products = Product.all }
        format.json { render :json => @prods }
      end
    end

   end

  # GET /products/1
  # GET /products/1.json
  def show
    render :json => {:data => @product }
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def search

    
       if params[:query]
       
        @prods = Product.search(params[:query])
        
        #format.html { @products = Product.search(params[:query]) }
        #format.json { render :json => @prods }  #@products = Product.search(params[:query]) 

        render  :json =>  {
                          :data => @prods
                          
                          


                }  
      else
         @prods = Product.all
        #@products = Product.all
        #format.html { @products = Product.all }
        render :json => {:data => @prods }
      end
   



    
  end



 




  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :cor, :descr)
    end
end

app/controllers/sidekiqexemplos_controller.rb
class SidekiqexemplosController < ApplicationController
  before_action :set_sidekiqexemplo, only: [:show, :edit, :update, :destroy]


  skip_before_action :verify_authenticity_token
  skip_before_filter :verify_authenticity_token
  skip_filter :verify_signed_out_user

  # GET /sidekiqexemplos
  # GET /sidekiqexemplos.json
  def index
    @sidekiqexemplos = Sidekiqexemplo.all
  end

  # GET /sidekiqexemplos/1
  # GET /sidekiqexemplos/1.json
  def show
  end

  # GET /sidekiqexemplos/new
  def new
    @sidekiqexemplo = Sidekiqexemplo.new
  end

  # GET /sidekiqexemplos/1/edit
  def edit
  end

  # POST /sidekiqexemplos
  # POST /sidekiqexemplos.json
  def create
    @sidekiqexemplo = Sidekiqexemplo.new(sidekiqexemplo_params)

    if @sidekiqexemplo.save

      render :json => {:data => @sidekiqexemplo }

      PygmentsWorker.perform_async(@sidekiqexemplo.id)
     

      

    else
      render :new
    end

      
    
  end

  # PATCH/PUT /sidekiqexemplos/1
  # PATCH/PUT /sidekiqexemplos/1.json
  def update
    respond_to do |format|
      if @sidekiqexemplo.update(sidekiqexemplo_params)
        format.html { redirect_to @sidekiqexemplo, notice: 'Sidekiqexemplo was successfully updated.' }
        format.json { render :show, status: :ok, location: @sidekiqexemplo }
      else
        format.html { render :edit }
        format.json { render json: @sidekiqexemplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sidekiqexemplos/1
  # DELETE /sidekiqexemplos/1.json
  def destroy
    @sidekiqexemplo.destroy
    respond_to do |format|
      format.html { redirect_to sidekiqexemplos_url, notice: 'Sidekiqexemplo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sidekiqexemplo
      @sidekiqexemplo = Sidekiqexemplo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sidekiqexemplo_params
      params.require(:sidekiqexemplo).permit(:tipo, :codigo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sidekiqexemplos_helper.rb
module SidekiqexemplosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="decoProteste">
<head>

  <title>Proteste</title>
  
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.10/angular-ui-router.js"></script>
  
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid" ng-view>
<%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :cor %><br>
    <%= f.text_field :cor %>
  </div>

  <div class="field">
    <%= f.label :descrição %><br>
    <%= f.text_field :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div ng-controller="ProductsCtrl">

<h1>Produtos</h1>


<!--
<div class="" style="position:absolute; right:40px;">
  
  <p><strong>Testar SideKiq:</strong></p>
      <%= link_to 'teste Sidekiq', new_sidekiqexemplo_path %>
</div>
 


<p><strong>Testar elasticSearch/Chewy (filtra a tres campos - nome cor descrição):</strong></p>
<%= form_tag products_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "search", name: nil %>

    
  </p>
<% end %>





<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Cor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.cor %></td>

        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

!-->


  
  <form class="form-inline">
  <div class="form-group">
    
    <input type="text" ng-model="query1" class="form-control" style="width:200px !important;">
    
  </div>
  <button class="btn btn-primary" ng-click="search()">Search</button>
  <button class="btn btn-primary"   data-toggle="modal" data-target="#myModal2" style="margin-left:70%;">Novo</button>
  </form>


  


  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Cor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr ng-repeat="p in res"> 
        <td>{{p.name}}</td>
        <td>{{p.price}}</td>
        <td>{{p.cor}}</td>
  
        
        <td><button class="btn btn-primary btn-xs" ng-click="showProd(p._id.$oid);" data-toggle="modal" data-target="#myModal">Show</button></td>
        <!--<td><button class="btn btn-warning btn-xs" ng-click="editProd(p._id.$oid);" data-toggle="modal" data-target="#myModal1">Edit</button></td>!-->
        <td><button class="btn btn-danger btn-xs" ng-click="deleteProd(p._id.$oid);">Delete</button></td>
      </tr>
   
  </tbody>
</table>



  <div class="" style="position:absolute; right:40px;">
  
   <!--<a class="btn btn-primary" href="/sidekiqexemplos/new">Teste SideKiq</a>


 <button class="btn btn-primary" ng-click="sidekiq();">SideKiq</button>!-->

</div>



<button class="btn btn-primary"   data-toggle="modal" data-target="#myModal3" style="margin-left:90%;">Sidekiq</button>







<div style="padding-left:100px !important;">

<form class="{{mostra}}">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="text" class="form-control" id="" placeholder="Linguagem a utilizar ex:(ruby)" ng-model="lang">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Código</label>
    <textarea rows="8" cols="50" class="form-control" ng-model="cod" placeholder="codigo a pigmentar
    ex: def teste   

    (....)

    end"></textarea>
    
  </div>
 
  <button type="" class="btn btn-default" ng-click="sidekiqnew();" >Submit</button>
</form>
</div>





<!-- Modal Show-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" ng-model="showform">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Produto</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Designação:</label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id=" " value="{{pro.data.name}}">
               
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Cor:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="" placeholder="" value="{{pro.data.cor}}">
              </div>
            </div>

            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Descrição:</label>
              <div class="col-sm-10">
               <textarea class="form-control" rows="5" id="">{{pro.data.descr}}</textarea>
               
              </div>
            </div>

             <div class="form-group">
              <label for="" class="col-sm-2 control-label">Preço:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="" placeholder="" value="{{pro.data.price}}">
              </div>
            </div>
           
            
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" >Guardar</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal Edit-->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Pigmentar o Códido (sidekiq exemplo)</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Designação:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control"  ng-model="prod.name">
               
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Cor:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="" ng-model="prod.cor">
              </div>
            </div>

            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Descrição:</label>
              <div class="col-sm-10">
               <textarea class="form-control" rows="5" id="" ng-model="prod.descr"></textarea>
               
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-sm-2 control-label">Preço:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="" placeholder="" ng-model="prod.price">
              </div>
            </div>
           
            
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="newProd(prod);" name="prodForm">Guardar</button>
        
      </div>
    </div>
  </div>
</div>


<!-- Modal create-->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Pigmentar o Códido (sidekiq exemplo)</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Designação:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control"  ng-model="prod.name">
               
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Cor:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="" ng-model="prod.cor">
              </div>
            </div>

            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Descrição:</label>
              <div class="col-sm-10">
               <textarea class="form-control" rows="5" id="" ng-model="prod.descr"></textarea>
               
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-sm-2 control-label">Preço:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="" placeholder="" ng-model="prod.price">
              </div>
            </div>
           
            
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="newProd(prod);" name="prodForm">Guardar</button>
        
      </div>
    </div>
  </div>
</div>




<!-- Modal sidekiq-->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Produto</h4>
      </div>
      <div class="modal-body">

          <form class="form-horizontal">
                <div class="form-group">
                  <label for="" class="col-sm-2 control-label">Linguagem:</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control"  placeholder="ex: Ruby" ng-model="sidekiqexemplo.tipo">
                  </div>
                </div>
                <div class="form-group">
                  <label for="" class="col-sm-2 control-label">Código</label>
                  <div class="col-sm-10">
                    <textarea rows="5" cols="5" class="form-control"  placeholder="def metodo
                    @products = Products.all
                    end" ng-model="sidekiqexemplo.codigo"></textarea> 
                  </div>
                </div>
               
                
          </form>

        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="sideTeste(sidekiqexemplo);" name="prodForm">Pigmentar!</button>
        
      </div>
    </div>
  </div>
</div>

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @product.cor %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @product.descr %>
</p>


<p><strong>Criticas:</strong></p>
<% if @product.criticas.size >0 %>
	


<% @product.criticas.each do |critica| %>
	
	<p><%= critica.content %></p>
<% end %>

<% else %>
	<p>sem criticas!!</p>

<% end %>




<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sidekiqexemplos/_form.html.erb
<%= form_for(@sidekiqexemplo) do |f| %>
  <% if @sidekiqexemplo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sidekiqexemplo.errors.count, "error") %> prohibited this sidekiqexemplo from being saved:</h2>

      <ul>
      <% @sidekiqexemplo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_area :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sidekiqexemplos/edit.html.erb
<h1>Editing sidekiqexemplo</h1>

<%= render 'form' %>

<%= link_to 'Show', @sidekiqexemplo %> |
<%= link_to 'Back', product_path %>

app/views/sidekiqexemplos/index.html.erb
<h1>Listing sidekiqexemplos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sidekiqexemplos.each do |sidekiqexemplo| %>
      <tr>
        <td><%= sidekiqexemplo.tipo %></td>
        <td><%= sidekiqexemplo.codigo %></td>
        <td><%= link_to 'Show', sidekiqexemplo %></td>
        <td><%= link_to 'Edit', edit_sidekiqexemplo_path(sidekiqexemplo) %></td>
        <td><%= link_to 'Destroy', sidekiqexemplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sidekiqexemplo', new_sidekiqexemplo_path %>

app/views/sidekiqexemplos/new.html.erb
<h1>sidekiq exemplo</h1>

<p>insira o tipo de linguagem e o respectivo código a "colorir"</p>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/sidekiqexemplos/show.html.erb
<!DOCTYPE html>


<div ng-controller="SideKiqCtrl">


<p>
  <strong>Tipo:</strong>
  <%= @sidekiqexemplo.tipo %>
</p>

<p>
  <strong>Codigo:</strong>

  <div>
  
  <%= @sidekiqexemplo.codigo.html_safe %>

  </div>
</p>

<button class="btn btn-primary" ng-click="backProds()">Voltar</button>

</div>